# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ml_models_pb2 as ml__models__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ml_models_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLModelServiceStub(object):
    """Service definition for ML model operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EmbedSentence = channel.unary_unary(
                '/ml_models.MLModelService/EmbedSentence',
                request_serializer=ml__models__pb2.EmbedSentenceRequest.SerializeToString,
                response_deserializer=ml__models__pb2.EmbedSentenceResponse.FromString,
                _registered_method=True)
        self.EmbedBatch = channel.unary_unary(
                '/ml_models.MLModelService/EmbedBatch',
                request_serializer=ml__models__pb2.EmbedBatchRequest.SerializeToString,
                response_deserializer=ml__models__pb2.EmbedBatchResponse.FromString,
                _registered_method=True)
        self.RerankDocuments = channel.unary_unary(
                '/ml_models.MLModelService/RerankDocuments',
                request_serializer=ml__models__pb2.RerankDocumentsRequest.SerializeToString,
                response_deserializer=ml__models__pb2.RerankDocumentsResponse.FromString,
                _registered_method=True)
        self.RewritePrompt = channel.unary_unary(
                '/ml_models.MLModelService/RewritePrompt',
                request_serializer=ml__models__pb2.RewritePromptRequest.SerializeToString,
                response_deserializer=ml__models__pb2.RewritePromptResponse.FromString,
                _registered_method=True)
        self.CompressPrompt = channel.unary_unary(
                '/ml_models.MLModelService/CompressPrompt',
                request_serializer=ml__models__pb2.CompressPromptRequest.SerializeToString,
                response_deserializer=ml__models__pb2.CompressPromptResponse.FromString,
                _registered_method=True)
        self.GetMemoryInfo = channel.unary_unary(
                '/ml_models.MLModelService/GetMemoryInfo',
                request_serializer=ml__models__pb2.GetMemoryInfoRequest.SerializeToString,
                response_deserializer=ml__models__pb2.GetMemoryInfoResponse.FromString,
                _registered_method=True)
        self.CleanupModels = channel.unary_unary(
                '/ml_models.MLModelService/CleanupModels',
                request_serializer=ml__models__pb2.CleanupModelsRequest.SerializeToString,
                response_deserializer=ml__models__pb2.CleanupModelsResponse.FromString,
                _registered_method=True)
        self.WarmupModels = channel.unary_unary(
                '/ml_models.MLModelService/WarmupModels',
                request_serializer=ml__models__pb2.WarmupModelsRequest.SerializeToString,
                response_deserializer=ml__models__pb2.WarmupModelsResponse.FromString,
                _registered_method=True)
        self.GetServerStatus = channel.unary_unary(
                '/ml_models.MLModelService/GetServerStatus',
                request_serializer=ml__models__pb2.GetServerStatusRequest.SerializeToString,
                response_deserializer=ml__models__pb2.GetServerStatusResponse.FromString,
                _registered_method=True)


class MLModelServiceServicer(object):
    """Service definition for ML model operations
    """

    def EmbedSentence(self, request, context):
        """Text embedding operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RerankDocuments(self, request, context):
        """Document reranking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RewritePrompt(self, request, context):
        """Prompt operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompressPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemoryInfo(self, request, context):
        """Server management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanupModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WarmupModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerStatus(self, request, context):
        """Health and status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EmbedSentence': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedSentence,
                    request_deserializer=ml__models__pb2.EmbedSentenceRequest.FromString,
                    response_serializer=ml__models__pb2.EmbedSentenceResponse.SerializeToString,
            ),
            'EmbedBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedBatch,
                    request_deserializer=ml__models__pb2.EmbedBatchRequest.FromString,
                    response_serializer=ml__models__pb2.EmbedBatchResponse.SerializeToString,
            ),
            'RerankDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.RerankDocuments,
                    request_deserializer=ml__models__pb2.RerankDocumentsRequest.FromString,
                    response_serializer=ml__models__pb2.RerankDocumentsResponse.SerializeToString,
            ),
            'RewritePrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.RewritePrompt,
                    request_deserializer=ml__models__pb2.RewritePromptRequest.FromString,
                    response_serializer=ml__models__pb2.RewritePromptResponse.SerializeToString,
            ),
            'CompressPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.CompressPrompt,
                    request_deserializer=ml__models__pb2.CompressPromptRequest.FromString,
                    response_serializer=ml__models__pb2.CompressPromptResponse.SerializeToString,
            ),
            'GetMemoryInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemoryInfo,
                    request_deserializer=ml__models__pb2.GetMemoryInfoRequest.FromString,
                    response_serializer=ml__models__pb2.GetMemoryInfoResponse.SerializeToString,
            ),
            'CleanupModels': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanupModels,
                    request_deserializer=ml__models__pb2.CleanupModelsRequest.FromString,
                    response_serializer=ml__models__pb2.CleanupModelsResponse.SerializeToString,
            ),
            'WarmupModels': grpc.unary_unary_rpc_method_handler(
                    servicer.WarmupModels,
                    request_deserializer=ml__models__pb2.WarmupModelsRequest.FromString,
                    response_serializer=ml__models__pb2.WarmupModelsResponse.SerializeToString,
            ),
            'GetServerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerStatus,
                    request_deserializer=ml__models__pb2.GetServerStatusRequest.FromString,
                    response_serializer=ml__models__pb2.GetServerStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ml_models.MLModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ml_models.MLModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLModelService(object):
    """Service definition for ML model operations
    """

    @staticmethod
    def EmbedSentence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_models.MLModelService/EmbedSentence',
            ml__models__pb2.EmbedSentenceRequest.SerializeToString,
            ml__models__pb2.EmbedSentenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_models.MLModelService/EmbedBatch',
            ml__models__pb2.EmbedBatchRequest.SerializeToString,
            ml__models__pb2.EmbedBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RerankDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_models.MLModelService/RerankDocuments',
            ml__models__pb2.RerankDocumentsRequest.SerializeToString,
            ml__models__pb2.RerankDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RewritePrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_models.MLModelService/RewritePrompt',
            ml__models__pb2.RewritePromptRequest.SerializeToString,
            ml__models__pb2.RewritePromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompressPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_models.MLModelService/CompressPrompt',
            ml__models__pb2.CompressPromptRequest.SerializeToString,
            ml__models__pb2.CompressPromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemoryInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_models.MLModelService/GetMemoryInfo',
            ml__models__pb2.GetMemoryInfoRequest.SerializeToString,
            ml__models__pb2.GetMemoryInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CleanupModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_models.MLModelService/CleanupModels',
            ml__models__pb2.CleanupModelsRequest.SerializeToString,
            ml__models__pb2.CleanupModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WarmupModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_models.MLModelService/WarmupModels',
            ml__models__pb2.WarmupModelsRequest.SerializeToString,
            ml__models__pb2.WarmupModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml_models.MLModelService/GetServerStatus',
            ml__models__pb2.GetServerStatusRequest.SerializeToString,
            ml__models__pb2.GetServerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
