from pymilvus import MilvusClient, DataType, Function, FunctionType, AnnSearchRequest, RRFRanker
from datetime import datetime, timezone
from typing import List
import os
import time
import schedule
import asyncio

from HybirdRAG.comp import MLModelClient
from langchain_core.documents import Document
from llama_index.core.node_parser import SentenceSplitter
from llama_index.core.embeddings import BaseEmbedding
from .text_processing import Formatter

schema = MilvusClient.create_schema()

index_params = MilvusClient.prepare_index_params()

bm25_function = Function(
    name="content_bm25_emb", # Function name
    input_field_names=["content"], # Name of the VARCHAR field containing raw text data
    output_field_names=["sparse"], # Name of the SPARSE_FLOAT_VECTOR field reserved to store generated embeddings
    function_type=FunctionType.BM25, # Set to `BM25`
)

DIMENSION = 1024

schema.add_field(field_name="id", datatype=DataType.INT64, is_primary=True, auto_id=True)
schema.add_field(field_name="content", datatype=DataType.VARCHAR, max_length=10000, enable_analyzer=True)
schema.add_field(field_name="title", datatype=DataType.VARCHAR, max_length=1000)
schema.add_field(field_name="page", datatype=DataType.INT64)
schema.add_field(field_name="source", datatype=DataType.VARCHAR, max_length=500)
schema.add_field(field_name="source_path", datatype=DataType.VARCHAR, max_length=1000)
schema.add_field(field_name="vector", datatype=DataType.FLOAT_VECTOR, dim=DIMENSION)
schema.add_field(field_name="add_at", datatype=DataType.INT64)
schema.add_field(field_name="chapter", datatype=DataType.INT64)
schema.add_field(field_name="section", datatype=DataType.INT64)
schema.add_field(field_name="sparse", datatype=DataType.SPARSE_FLOAT_VECTOR)
schema.add_function(bm25_function)

index_params.add_index(
    field_name="sparse",
    index_type="SPARSE_INVERTED_INDEX",
    metric_type="BM25",
    params={
        "inverted_index_algo": "DAAT_MAXSCORE",
        "bm25_k1": 1.2,
        "bm25_b": 0.75
    }
)

index_params.add_index(
    field_name="vector",
    index_type="IVF_FLAT",
    metric_type="COSINE",
    params={
        "nlist": 128
    }
)

# Removed text_vector index since the field doesn't exist in schema

# Fields allowed for insert (schema fields except id=auto_id and sparse=generated by function)
INSERT_FIELDS = {"content", "title", "page", "source", "source_path", "vector", "add_at", "chapter", "section"}


class VectorRAGPipeline:
    def __init__(self, milvus: MilvusClient, embedding: BaseEmbedding, collection_name: str = "vector_rag"):
        self.milvus = milvus
        self.index = index_params
        self.embedding = embedding
        self.collection_name = collection_name
        if not self.milvus.has_collection(collection_name=collection_name):
            self.milvus.create_collection(collection_name=collection_name, schema=schema, index_params=self.index)
        
        # Load the collection to enable querying
        try:
            self.milvus.load_collection(collection_name=collection_name)
        except Exception as e:
            print(f"⚠️ Collection loading warning: {e}")
            # Try to create indexes and reload
            try:
                print("🔄 Attempting to create indexes...")
                self.milvus.create_index(collection_name=collection_name, index_params=self.index)
                self.milvus.load_collection(collection_name=collection_name)
                print("✅ Indexes created and collection loaded successfully")
            except Exception as e2:
                print(f"❌ Failed to create indexes: {e2}")
                # Continue anyway


    def add_document(self, document: List[dict]):
        rows = []
        for doc in document:
            # Set computed and default values for schema fields only
            doc["vector"] = list(self.embedding.embed_sentence(doc["content"]))
            doc["add_at"] = int(doc.get("add_at", time.time()))
            doc["chapter"] = doc.get("chapter", 0)
            doc["section"] = doc.get("section", 0)
            doc["source"] = doc.get("source", "unknown")
            doc["source_path"] = doc.get("source_path", "")
            doc["title"] = doc.get("title", "")
            doc["page"] = doc.get("page") if doc.get("page") is not None else 0
            # Keep only schema-defined fields (exclude id; sparse is generated by collection function)
            row = {k: doc[k] for k in INSERT_FIELDS if k in doc}
            rows.append(row)
        self.milvus.insert(collection_name=self.collection_name, data=rows)

    def _deduplicate_results(self, results):
        """Deduplicate search results based on block IDs."""
        if not results:
            return results
        
        deduplicated = []
        seen_ids = set()
        
        for hit in results:
            if hasattr(hit, '__iter__'):  # Handle HybridHits
                hit_deduplicated = []
                for hit_item in hit:
                    # Get block ID from the hit item
                    block_id = self._get_block_id(hit_item)
                    if block_id and block_id not in seen_ids:
                        seen_ids.add(block_id)
                        hit_deduplicated.append(hit_item)
                
                if hit_deduplicated:
                    # Create a new hit object with deduplicated items
                    deduplicated.append(hit_deduplicated)
            else:
                # Handle individual hit items
                block_id = self._get_block_id(hit)
                if block_id and block_id not in seen_ids:
                    seen_ids.add(block_id)
                    deduplicated.append(hit)
        
        return deduplicated

    def _get_block_id(self, hit_item):
        """Extract block ID from a hit item."""
        try:
            # Try different ways to get the ID
            if hasattr(hit_item, 'id'):
                return str(hit_item.id)
            elif hasattr(hit_item, 'entity') and hasattr(hit_item.entity, 'id'):
                return str(hit_item.entity.id)
            elif isinstance(hit_item, dict):
                if 'id' in hit_item:
                    return str(hit_item['id'])
                elif 'entity' in hit_item and isinstance(hit_item['entity'], dict) and 'id' in hit_item['entity']:
                    return str(hit_item['entity']['id'])
            
            return None
        except Exception:
            return None

    def query(self, query: List[str], limit: int = 20, filters: List[str] = None):  # Increased default limit
        # Handle both single query and list of queries
        if isinstance(query, str):
            query_list = [query]
        else:
            query_list = query
        
        # For multiple queries, we'll combine them into a single embedding
        # This gives us better coverage across all query terms
        try:
            query_embedding = self.embedding.embed_batch(query_list)
            if query_embedding is None or len(query_embedding) == 0:
                print("⚠️  Embedding generation failed, returning empty results")
                return []
        except Exception as e:
            print(f"⚠️  Embedding generation error: {e}")
            return []
        
        # Fallback to individual embeddings if batch fails
        if query_embedding is None:
            print("⚠️  Batch embedding failed, falling back to individual embeddings")
            query_embedding = [self.embedding.embed_sentence(q) for q in query_list]
            # For hybrid search, we need a single combined embedding
            # Average the embeddings if multiple queries
            if len(query_embedding) > 1:
                import numpy as np
                query_embedding = [np.mean(query_embedding, axis=0).tolist()]
            else:
                query_embedding = query_embedding
        
        search_params = {
            "output_fields": ["id", "content", "add_at", "chapter", "section"]
        }
        if filters:
            search_params["filter"] = " AND ".join(filters)

        sparse_search_params = search_params.copy()
        sparse_search_params["params"] = {'drop_ratio_search': 0.6}

        full_text_search_params = {"metric_type": "BM25"}
        full_text_search_req = AnnSearchRequest(
            query_list, "sparse", full_text_search_params, limit=limit
        )

        dense_search_params = {"metric_type": "COSINE"}
        dense_req = AnnSearchRequest(
            query_embedding, "vector", dense_search_params, limit=limit
        )

            
        # Use simple vector search instead of hybrid search to avoid the error
        try:
            results = self.milvus.hybrid_search(
                    self.collection_name,
                    [full_text_search_req, dense_req],
                    ranker=RRFRanker(),
                    limit=limit,
                    **sparse_search_params
                )
            # Deduplicate results before returning
            deduplicated_results = self._deduplicate_results(results)
            return deduplicated_results
        except Exception as e:
            print(f"Vector search failed: {e}")
            # Fallback to simple vector search
            try:
                if query_embedding is not None:
                    results = self.milvus.search(
                        collection_name=self.collection_name,
                        data=query_embedding,
                        anns_field="vector",
                        param={"metric_type": "COSINE"},
                        limit=limit,
                        **search_params
                    )
                    return self._deduplicate_results(results)
                else:
                    print("⚠️  Query embedding is None, returning empty results")
                    return []
            except Exception as fallback_e:
                print(f"⚠️  Fallback vector search also failed: {fallback_e}")
                return []